language: python
python:
- '3.6'
jobs:
  include:
  - stage: Test
    install:
    - python -m pip install -r requirements.txt
    - python -m pip install pytest-cov coveralls
    script:
    - python -m pytest reqREST/Tests/ --cov=./ -v
    after_success:
    - coveralls
  - stage: Deploy to PyPI
    env:
      secure: "P1RZaIfWHXn7dyYBpcQBg82E23ZWT4QMLFQDLEMAkudfK/WlVqcZWbno9W7mfDn4QobqIQCo7GMe4kEKSRJqEK0Fn9lj+hnwPNUihSCPadu8BNlEOcowq2/AXhmaT0aTS8ehNtkeQLorrf2hcb9rwuO+Pqc9GmU21h42XwbHFvPHf6D44QQRX4qWpaffWyDiGZTFolQAil2jXclBKog6iaiTFbXCgRhnyEF1MYx0T7ooNrolqz8gR2gIEDB/BgASULHk4otRbZvYdUGpO+9ykc1MGO3nHV6hDSpNACICfEvwNhH0nuEO6bmxF7KhBxPDjUikatTc9cU3+T17D3afesAmO8sCfRuoCVZd+ohVixMu3nUB6+jD7XwAul5U6c5VfdX7aPQZEkxW+4ffo+Ei9BmnWxKFxGBYHkKkOUJuzw1t6jJJ63JOVrCiNRJxI763TUPFq+6/zz35alEUJCqhuGDQ6dDbk2MIEgLQusgNmBER8UHVYF3S/DKdeoMmU8AmXPm9Nt12efWLHp1t12plPgGy7szm5+W70+mSNN3begVtXsRZE4Xf4hE81COd9pKc5gSpvgMkENFQofdSrZcJ+aP0wrCqfXXqjKNDpSj5Pz3xy+bBIQ9jCIBzPV0ny3Tz3waQXeM6q2OL/jweAXyaXqQItwjmQy8ingxRbH3QkFI="
    language: python
    python: 3.6
    script:
    - git remote rm origin
    - git remote add origin https://${GITHUB_TOKEN}@github.com/rorymurdock/reqREST.git >/dev/null 2>&1
    - git fetch
    - git checkout master
    - python3 increment_version.py
    - git add -u
    - git commit -m "[ci skip] version changed"
    - git push --set-upstream origin master >/dev/null 2>&1
    deploy:
      provider: pypi
      user: rorymurdock
      password:
        secure: "JDYCJcyI4SuaCYuugQCWu2znXUEQqu+DxXS4QpkPgv5lTFCAgSsL4m9PdsgQ/TI65noxVT6pCiKiGVikZbzRqN/P8Y5qsDvMThwcOvYEZSGohCaM9EgGXTtuxm27cRNs8DJVG8JN2v1WkFTS7WgvglMen/DRiu+sM03/K/jARzKFfwY1FKYUNSvDmV20K6PnnO4+46zdp7VcYyhVwCppI14FmTEVLz8QeL/3HrdaxsYiEX9joAAav9AaicwtamJ9w86Mj5RV5gB5YwQjtOvRVY0SgbpOyKzzcW0/cl223VM3L/jwx5tdAbfvehDVeTo/pnRLo5uD66J4hFdLJWVa66BcPGtGTcde6TxCJIkGdUjgQ+LpoCA9z8GDQ99bZdi/uAK8XRw0LRjZc7qmTPM7bcQVltjtRLoWF8/1A/6mtD0kKgjIM7T+gp5TpGaIR1jfIKXZeSIngvmdtZvnh6sex/csh/43aUi039hlm5q9APv8ISyIS6SVUSN6PHatRE3QPDXTxqgsJHblEpLC5a+yZoJ1vTAArjzqMPHP8SbeRV/GPvLqBs0rG6qZZJ5fMibMFVW+9ulNsBgXe8iRQuG3u+MIBi1eX6JI+YNtcJp7ug3OSeX3csPTjdJWJqeZi6biqbl2QO1CemJcBcHFQ/jgFj2jEgurUUuvEeXv+cVb3t4="

stages:
- test
- name: Deploy to PyPI
  if: "(branch = master)"
